bind and other updates (https://app.asana.com/0/114313002471895/237280691539636)
firstandthird/runtask pull request #9
Opened 2017-01-08 06:28 UTC by orthagonal

2017-01-15 23:01 UTC, jgallen23 requested changes

2017-01-15 23:01 UTC, jgallen23 commented on index.js
> +        fn = fn.bind({ blah: '123' });
might want to check this

2017-01-15 23:01 UTC, jgallen23 commented on index.js
> +    fn = fn.execute ? fn.execute : fn;
lets remove this

2017-01-15 23:01 UTC, jgallen23 commented on index.js
> +    if (this.options.bind) {
this logic should be moved down after the array check, then you don't need the function check

2017-01-16 00:08 UTC, orthagonal commented on index.js
> +    fn = fn.execute ? fn.execute : fn;
remove the check for fn.execute?  don't we need to be able to run it whether it's a runkit class or just a function?

2017-01-16 00:28 UTC, jgallen23 commented on index.js
> +    fn = fn.execute ? fn.execute : fn;
we wrap the call on the runkit side anyways, no need to tie the two together

2017-01-18 18:56 UTC, jgallen23 requested changes

2017-01-18 18:56 UTC, jgallen23 commented on index.js
> +    if (!fn) {
this needs to be above bind

2017-01-18 19:25 UTC, merged